workflows:
  maui-android-build:
    name: ".NET MAUI Android Build"
    max_build_duration: 30
    environment:
      vars:
        DOTNET_VERSION: "8.0.203"
      groups:
        - keystore_credentials # αν χρειάζεσαι υπογραφή APK
    scripts:
      - name: Εγκατάσταση .NET SDK
        script: |
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version $DOTNET_VERSION
          export PATH=$HOME/.dotnet:$PATH
          dotnet --info

      - name: Εγκατάσταση MAUI workload
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet workload install maui

      - name: Restore dependencies
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet restore MyMauiApp.sln

      - name: Build .NET MAUI Android
        script: |
          export PATH=$HOME/.dotnet:$PATH
          dotnet publish MyMauiApp/MyMauiApp.csproj -f net8.0-android -c Release -o ./output/android

    artifacts:
      - output/android/**/*.apk
